"""added cloud_app table and added first_name, last_name 

Revision ID: 37393ddf3f5b
Revises: d05dd3207993
Create Date: 2023-06-13 20:56:06.475114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37393ddf3f5b'
down_revision = 'd05dd3207993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_cloud', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'app_cloud', ['code'])
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'app_cloud', type_='unique')
    op.drop_column('app_cloud', 'code')
    # ### end Alembic commands ###
