"""change User_id to user_id in the CloudAppUser

Revision ID: ebb8858a4b5e
Revises: 37393ddf3f5b
Create Date: 2023-07-01 13:05:33.022513

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision = 'ebb8858a4b5e'
down_revision = '37393ddf3f5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('app_cloud_user_User_id_fkey', 'app_cloud_user', type_='foreignkey')
    op.alter_column('app_cloud_user', 'User_id', new_column_name='user_id')
    op.create_foreign_key(None, 'app_cloud_user', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_cloud_user', type_='foreignkey')
    op.alter_column('app_cloud_user', 'user_id', new_column_name='User_id')
    op.create_foreign_key('app_cloud_user_User_id_fkey', 'app_cloud_user', 'user', ['User_id'], ['id'])
    # ### end Alembic commands ###
