name: Push to Space

on:
  push:
    branches:
    - main

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deta Space Deployment Github Action
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          project_id: ${{ secrets.SPACE_ID }}
          project_directory: ./backend/
          space_push: true
          list_on_discovery: true
      - shell: cmd
        env:
          SPACE_ACCESS_TOKEN: ${{ secrets.SPACE_ACCESS_TOKEN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
        run: |
          deta run --project-id $SPACE_ID --access-token $SPACE_ACCESS_TOKEN --watch

